### ISSUE TITLE
Sigma Point Fix

### ISSUE THREAD

**Issue by borcuttjahns** [meyer-lab/cell-selective-ligands#175]
It seems as though the sigma point method handles R1hi R2hi strangely when compared to other populations (namely R1hi R2lo and R1lo R2hi). This is evidenced by the optimization figure (figure 6) where greater selectivity is achieved for R1lo R2hi than R1hi R2hi (shouldn't be possible) as well as the new handling of the population to population comparisons (fig 4) where some strangeness was occurring.

**Comment by cyrillustan** [comment]
For figure 6, I don't think that is because of the sigma point though. R1loR2hi has higher selectivity than R1hiR2hi in older figures too. What is the strangeness you found in figure 4?

**Comment by borcuttjahns** [comment]
That shouldn’t be possible though, as R1hi R2hi should always have higher binding than R1lo R2hi - so even at R1lo R2hi’s optimum, it’s selectivity should be lower. And the weirdness I was referring to was what you showed me via video about the draft of those population comparisons.

**Comment by cyrillustan** [comment]
Okay, I'll look into these.

**Comment by cyrillustan** [comment]
I have made the changes to fix the issues you raised. Take a look.
